[package]
name = "papi-wasm-provider"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
smoldot-light = { version = "1.0.0", default-features = false }
smoldot = { version = "1.0.0", default-features = false, features = ["std"] }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
futures = "0.3"
futures-util = "0.3"
futures-timer = { version = "3", features = ["wasm-bindgen"] }
web-sys = { version = "0.3", features = [
    "BinaryType",
    "CloseEvent",
    "console",
    "Event",
    "MessageEvent",
    "WebSocket",
] }
js-sys = "0.3"
web-time = "1"
pin-project = "1"
send_wrapper = "0.6"
getrandom = { version = "0.2", features = ["js"] }
tracing = { version = "0.1", default-features = false }
thiserror = "2"
